version: '3.1'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    volumes:
      - storage:/storage
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
  storage:
